runtime: go
api_version: go1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /index.html
  static_files: static/index.html
  upload: static/index.html
- url: /app/(.*\.vue)$
  static_files: app/\1
  upload: app/.*\.vue$
  mime_type: text/html
  application_readable: true
- url: /static
  static_dir: static
- url: /.*
  script: _go_app